### ISSUE TITLE
npm publish (again :D)

### ISSUE THREAD

**Issue by zyberspace** [gwTumm/node-teamspeak#23]
Hi, at the moment the latest version at [npm](https://www.npmjs.com/package/node-teamspeak) is v1.04, but with this version, it is somehow not possible to have multiple Client-instances open in one project (yeah, i actually need this :D ).

But with the latest version from the repository it works just fine (v1.0.9), so could you pls publish it?

Also you should consider instant publishing every time you change the version in the `package.json`.
If you want to mark it as unstable first you can suffix it with `-rc1`, `-rc2` and so on. But this would be even more trouble (like in time you need to spend).

Edit: If you really have no time to publish on npm when a new version is out, you could also add me as maintainer for this project on npm (`npm owner add zyberspace`), so i can do the publish thing for you.
But of course you need to trust me for this :P

**Comment by Ahmed-90** [comment]
ye had the same issue everytime i clone my project :cry: 
quick fix is to point npm to git directly ```npm i -S gwTumm/node-teamspeak```  for the new version

**Comment by timklge** [comment]
Sorry for the long response time, I am not using this library anymore and can't test any new releases atm :/. I pushed 1.0.10 to npm just now.

I also added you as an owner on npm, thanks for your efforts. Feel free to push updates at any time. I would still appreciate pull requests for every change here doe :).
