### ISSUE TITLE
How does it receive text messages?

### ISSUE THREAD

**Issue by izy521** [gwTumm/node-teamspeak#26]
I'm aware of using the 'servernotifyregister' event to register the query client to receive text messages, but where do I go to log them to the terminal?

``` javascript
client.send('severnotifyregister', {event: 'textchannel'}, function(err, response, rawResponse) {

});
```

This is what my code snippet looks like. If I have it console.log(response), I get undefined. That's expected as I assume the response is the immediate response from the server after the event's been executed. Can someone help me out?

Oh man, I'm a moron, it's right there at the bottom of the page. Sorry.

**Comment by Shic1983** [comment]
Can you post your code of how your got this work ? I'm struggling....

**Comment by izy521** [comment]
Oh, that was so long ago, I don't think I continued down that avenue. I'll give you what I saved when I stopped, though. Here you go: https://gist.github.com/izy521/cdbc44576e0376e7182a. I think you send the `servernotifyregister` and receive data through debug, but I can't remember.
