### ISSUE TITLE
Register to notifications

### ISSUE THREAD

**Issue by Kaos1337** [gwTumm/node-teamspeak#30]
Hello,
can I do something that waits for the connection of every user and reply with an "hello" to anyone just joined?
I see that I can "register to notifications", but can you provide an example?
Thanks.

**Comment by dtheb** [comment]
Hi,

its already written on the readme file you just need to register for the server events and listen to "cliententerview" event

read the teamspeak query manual pdf file this module is simply an interface for that

**Comment by Kaos1337** [comment]
Perfect, thank you.
