### ISSUE TITLE
TeamSpeak sends events like 'clientmoved' twice

### ISSUE THREAD

**Issue by mamayer** [gwTumm/node-teamspeak#33]
Reproduce:

**Serverquery**

```
login user password
error id=0 msg=ok
use 1
error id=0 msg=ok
servernotifyregister event=server
error id=0 msg=ok
servernotifyregister event=channel id=0
error id=0 msg=ok
```

Switch channel _once_

```
notifyclientmoved ctid=830 reasonid=0 clid=9
notifyclientmoved ctid=830 reasonid=0 clid=9
```

This (of course) also affects node-teamspeak.

Possible solution: In index.js change

``` javascript
socket.on("connect", function(){
// ...
   } else if(s.indexOf("notify") === 0){
      s = s.substr("notify".length);
      response = parseResponse(s);
      self.emit(s.substr(0, s.indexOf(" ")), response);
    } else if(executing) {
// ...
});
```

to

``` javascript
var prevresponse = {};
socket.on("connect", function(){
// ...
   } else if(s.indexOf("notify") === 0){
      s = s.substr("notify".length);
      response = parseResponse(s);
      if(JSON.stringify(prevresponse) != JSON.stringify(response)){
         self.emit(s.substr(0, s.indexOf(" ")), response);
         self.emit('notification', s.substr(0, s.indexOf(" ")), response);    // notification on ALL notifications
      }
      prevresponse = response;
    } else if(executing) {
// ...
});
```

**Comment by mamayer** [comment]
I just found the pullrequest of @izy521 https://github.com/gwTumm/node-teamspeak/pull/27/commits/7bebb907a8bb3360b8829e871735393200666860 which is a simular solution to "notification on ALL notifications".
Is there any maintained fork, that has it, too?

**Comment by dtheb** [comment]
thats just how teamspeak works :/  client move event is on both server and channel level so you have to subscribe to only one of them ... in most cases subscribe to server alone is the best option

**Comment by zyberspace** [comment]
> thats just how teamspeak works :/

yep, exactly. Also if you register for both events (like OP did), you of course also receive both ones. No need for a change here.

**Comment by mamayer** [comment]
The problem is, that you need to register for both events to get all other events. If I only subscribe to server I dont get moves and if I subscribe to channel only, I don't get joins/leaves, etc. :(

**Comment by zyberspace** [comment]
Yeah but that's something your bot / client needs to handle, not this library. This library is simple an abstraction of the teamspeak query protocol.

And if the query sends us two events it's the job of node-teamspeak to also emit these two events.

**Comment by mamayer** [comment]
Hmm, true from that point of view.
